config/routes.rb
Rails.application.routes.draw do
  resources :employees

  resources :sales do
    collection do
      get :payment
    end
  end

  resources :customers

  resources :cars

  root 'dashboard#index'

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :car
  belongs_to :customer
  belongs_to :employee

  def self.calculate_payment_table(total_price = 0, year = 0, interest = 0)
    Rails.logger.debug "Inputs: #{total_price} #{year} #{interest}"
    payment = []
    (0..year).each do |t|
      payment << (interest*total_price*(1+interest)**(year*12))/(((1+interest)**(year*12))-1)
    end
    return payment
  end

  def calculate_payment_table
    return self.class.calculate_payment_table(self.total_price,self.interest,self.year)
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    @payment_array = @sale.calculate_payment_table
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def interest
    rate = params[:rate]
    time = params[:time]
    starting_amount = params[:amount]
    @payment_array = Sale.calculate_payment_table(starting_amount.to_i, time.to_i, rate.to_f)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:customer_id, :employee_id, :car_id,:total_price, :interest, :year, :status,:date)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :customer %><br>
      <%= f.collection_select :customer_id, Customer.all, :id, :cus_name %>
    </div>
    <div class="field">
      <%= f.label :employee %><br>
      <%= f.collection_select :employee_id, Employee.all, :id, :emp_name%>
    </div>
    <div class="field">
      <%= f.label :color %><br>
      <%= f.collection_select :car_id, Car.all, :id, :car %>
    </div>

    <div class="field">
      <%= f.label :total_price %><br>
      <%= f.text_field :total_price%>
    </div>

    <div class="field">
      <%= f.label :interest %><br>
      <%= f.text_field :interest%>
    </div>

    <div class="field">
      <%= f.label :year %><br>
      <%= f.select :status, options_for_select([['3'], ['4'],['5']],:selected => :status)%>
    </div>

    <div class="field">
      <%= f.label :status %><br>
      <%= f.select :status, options_for_select([['Quote'], ['Sale']],:selected => :status) %>
    </div>
    <div class="field">
      <%= f.label :date %><br>
      <%= f.date_select :date %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<div id="interest_table" class="table-format"></div>

app/views/sales/_interest_table.erb
<table class="CSSTableGenerator" width="30%">
  <th>Year</th>
  <th>Amount</th>
  <% @payment_array.each_with_index do |p,n|  %>
      <tr>
        <td><%= n %></td>
        <td><%= p.round(2) %></td>
      </tr>
  <% end %> %>
</table>

app/views/sales/edit.html.erb
<div id="carbody">
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>
</div>

app/views/sales/index.html.erb
<div id="carbody">
<p id="notice"><%= notice %></p>

<h1>Sales</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Employee</th>
      <th>Car</th>
      <th>Total Price</th>
      <th>Interest</th>
      <th>Year</th>
      <th>Status</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.customer.f_name%></td>
        <td><%= sale.employee.f_name %></td>
        <td><%= sale.car.car %></td>
        <td><%= sale.total_price %></td>
        <td><%= sale.interest %></td>
        <td><%= sale.year %></td>
        <td><%= sale.status %></td>
        <td><%= sale.date %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>
</div>

app/views/sales/interest.js.erb
$('#interest-table').html("<%= j (render 'interest_table') %>")

app/views/sales/new.html.erb
<div id="carbody">
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>
</div>

app/views/sales/show.html.erb
<div id="carbody">
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @sale.customer.f_name%>
</p>

<p>
  <strong>Employee:</strong>
  <%= @sale.employee.f_name %>
</p>

<p>
  <strong>Car:</strong>
  <%= @sale.car.car %>
</p>


<p>
  <strong>Total price:</strong>
  <%= @sale.total_price %>
</p>

<p>
  <strong>Interest rate:</strong>
  <%= @sale.interest %>
</p>

<p>
  <strong>Year:</strong>
  <%= @sale.year %>
</p>


<p>
  <strong>Status:</strong>
  <%= @sale.status %>
</p>

<p>
  <strong>Date:</strong>
  <%= @sale.date %>
</p>

<%= render 'interest_table' %>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>
</div>